// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp1KWwpdxV4SaTtXPRSH3gsMKjwtEoYZ4',
    appId: '1:1063904952978:ios:82992a18b76e5d7c4e9c4b',
    messagingSenderId: '1063904952978',
    projectId: 'caffeinestudio-chess',
    databaseURL: 'https://caffeinestudio-chess-default-rtdb.firebaseio.com',
    storageBucket: 'caffeinestudio-chess.appspot.com',
    iosBundleId: 'br.com.caffeinestudio.chess',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkHHpl-IlHOVC2ZNnJmReikcwxcipRI7g',
    appId: '1:1063904952978:android:7106b88d339adfb54e9c4b',
    messagingSenderId: '1063904952978',
    projectId: 'caffeinestudio-chess',
    databaseURL: 'https://caffeinestudio-chess-default-rtdb.firebaseio.com',
    storageBucket: 'caffeinestudio-chess.appspot.com',
  );

}